name: OIDC Assume Role
# Controla quando a ação será executada. Invoca o workflow em eventos push, mas somente para o branch principal
on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
    secrets: {}
# A permissão pode ser adicionada no nível do job ou do workflow  
permissions:
  id-token: write   # Isso é necessário para solicitar o JWT
  contents: read    # Isso é necessário para ações/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::104538124807:role/GitHubAction-FrontWorkoutApp #altere para refletir a ARN da sua IAM role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.region }}
      # Olá da AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Export credentials
        id: export
        run: |
          echo "aws-access-key-id=${{ env.AWS_ACCESS_KEY_ID }}" >> $GITHUB_OUTPUT
          echo "aws-secret-access-key=${{ env.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_OUTPUT
          echo "aws-session-token=${{ env.AWS_SESSION_TOKEN }}" >> $GITHUB_OUTPUT
