name: Deploy to S3

on:
  push:
    branches: [ "main" ]

# A permissão pode ser adicionada no nível do job ou do workflow  
permissions:
  id-token: write   # Isso é necessário para solicitar o JWT
  contents: read    # Isso é necessário para ações/checkout

jobs:

    
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ needs.assume-oidc.outputs.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ needs.assume-oidc.outputs.aws-secret-access-key }}
      AWS_SESSION_TOKEN: ${{ needs.assume-oidc.outputs.aws-session-token }}
      CLOUDFRONT_ID: EP8T3JBQQ41HE
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # ou a versão do seu projeto

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build --if-present
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::104538124807:role/GitHubAction-FrontWorkoutApp
        aws-region: us-east-1
    - name: Upload to S3
      run: |
        aws s3 sync ./dist s3://front-workout-app/ --delete
    - name: Invalidate Cache
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        PATHS: "/*"
        AWS_REGION: 'us-east-1'
        DISTRIBUTION: ${{ env.CLOUDFRONT_ID }}
    